### ISSUE TITLE
Make marker pop-ups self-explaining

### ISSUE THREAD

**Issue by StefanBrand** [WeAreFairphone/fprsmap#12]
At the moment, I fear that people don't know that every marker has a popup, if they don't accidentally click on one. How can we make marker pop-ups self-explaining?

**Comment by Roboe** [comment]
Although I think the behaviour is quite known for the mayority of the users, I propose an improvement for that: we can open and close the popup when the mouse "touch" the marker.
Reference:
* Leaflet's events: http://leafletjs.com/reference.html#events
* Events documentation: http://leafletjs.com/reference.html#marker-options (below that, section Events)

**Comment by newluck77** [comment]
What if we simply make one marker "Amsterdam Fairphone HQ", which is 
open by default?

PS.: Hovering doesn't work with touchscreens... I'll have to conduce 
some experiments with test persons to see how they react on the markers 
(if they find the popups)... ;)

Am 11.09.2016 um 02:13 schrieb Roberto M.F.:

**Comment by Roboe** [comment]
> What if we simply make one marker "Amsterdam Fairphone HQ", which is open by default?

Seems fair enough (pun intended!)

**Comment by Roboe** [comment]
In which layer should we implement the Fairphone headquarters marker? Stand-alone?

Open it by default is pretty easy: http://leafletjs.com/reference.html#popup

**Comment by StefanBrand** [comment]
Stand alone, I'd say. It's not bad if it's there all the time, is it? :) 

The popup could include a link to the website and the address and telephone number (like with the shop popups).

**Comment by StefanBrand** [comment]
If somebody comes up with a better idea than [mine above](https://github.com/WeAreFairphone/fprsmap/issues/12#issuecomment-246169117), please post it here. :slightly_smiling_face:
