### ISSUE TITLE
Markers on top of each other

### ISSUE THREAD

**Issue by Roboe** [WeAreFairphone/fprsmap#18]
As commented in #13:

@StefanBrand 
> What if two markers on two different layers are on top of each other?

The below article may be of help:
https://asmaloney.com/2015/06/code/clustering-markers-on-leaflet-maps/

**Comment by StefanBrand** [comment]
Oh no, I thought I had properly updated one single commit when I used `git rebase -i HEAD~3`... Ö

**Comment by Roboe** [comment]
Wow... multiple `rebase` & `git push -f`? Although there's a single commit, GitHub registers all of the revisions referencing this issue, hahaha
