### ISSUE TITLE
Change basemap tile server

### ISSUE THREAD

**Issue by StefanBrand** [WeAreFairphone/fprsmap#20]
Since OpenStreetMaps' [Tile usage policy](https://wiki.openstreetmap.org/wiki/Tile_usage_policy) forbids to build apps with tiles fetched from their tile server we should switch to a [different provider](https://wiki.openstreetmap.org/wiki/Tile_usage_policy#Alternative_OpenStreetMap_Tile_Providers).

What about [Stamen Watercolour](http://maps.stamen.com/watercolor/#3/56.12/16.70) (with donation) or [Carto Positron](https://carto.com/location-data-services/basemaps/) (the light basemap with 75,000 gratis map views)?

PS.: I'm of course very open for other suggestions!

**Comment by Roboe** [comment]
We can get some info from the recent GNOME/gnome-maps limits issue:
* http://www.omgubuntu.co.uk/2016/07/gnome-maps-dead-end-mapquest
* http://www.omgubuntu.co.uk/2016/07/gnome-maps-new-tile-service

**Comment by StefanBrand** [comment]
Mapbox, which they use now, requires a log-in (in order to receive an 
access token).

On the other hand it has **a lot** of features, amongst them custom map 
designs, a Geocoding API, etc.: 
https://www.mapbox.com/help/how-mapbox-works/

Am 16.09.2016 um 20:01 schrieb Roberto M.F.:

**Comment by StefanBrand** [comment]
For now I would go for Carto Positron (or Dark Matter??? :smiling_imp: ) because it goes best with our colorful markers.

**Comment by StefanBrand** [comment]
Ok, I ran into a problem. Carto [Terms of Service - Free Basemaps (pdf)](https://drive.google.com/a/cartodb.com/file/d/0B3OBExqwT6KJM29vWmdmcXdKLTg/view) cites the following: 

> We grant you a non­exclusive, revocable, worldwide, non­transferable, non­sublicensable right and license to use the Services for non­commercial purposes. For purposes of these terms, a commercial purpose is one which is primarily intended for or directed toward private monetary compensation or other commercial advantage. If you have any question as to whether your intended use constitutes a commercial purpose, we request you contact us prior to such use.

Mapbox is less restrictive, [allowing](https://www.mapbox.com/tos/#[YmouMuan])

>commercial applications publicly accessible without charge

On the other hand they require a [watermark with their logo](https://www.mapbox.com/help/mapbox-logo/).

@Roboe I'm pretty sure that our map counts as commercial as soon as it is incorporated into Fairphone's new webpage. Should I contact Carto nevertheless or do we go for Mapbox right away?

**Comment by StefanBrand** [comment]
So what about it? :)

**Comment by Roboe** [comment]
Sorry, I overlooked this issue.

Our map is **not** a comercial product, it's a **community project** not intended for earning money. But with the vicissitude that we have some kind of official support from Fairphone: they'll lend us a subdomain and open up their data (although that'll be available for any other project, not only ours). They could be benefited by the existence of the map, of course, but we were [born in the Community Forum](https://forum.fairphone.com/t/do-you-know-an-open-source-alternative-to-embedded-maps/5088) for the community (Fairphone devices' owners).

So I think we should reach them. They are Spanish people (I meet one Carto developer on h4ckademy), so they **must** be kind people, ;) _(ok, I'm not being impartial here, I'm Spanish, :laughing:)_

Not needing any API key is very convenient for us, BTW.

About the cutomization, AFAIK MapBox uses a fork of Leaflet and Carto tiles can be [easily](https://carto.com/location-data-services/basemaps/#documentation) integrated with our current codebase.

**Comment by StefanBrand** [comment]
> Radikal is a proprietary and non-free-to-use font: https://www.myfonts.com/fonts/nootype/radikal/licensing.html

Yeah, that's what they [were saying ](https://forum.fairphone.com/t/finding-a-european-fairphoners-logo/18575/3?u=stefan)over at the Fairphone Forum.

> So I think we should reach them. 

I'm looking forward to the response of your contact person. It would be great if we could use [CARTO Positron](https://carto.com/location-data-services/basemaps/), it's simply the best basemap for our purpose, in my opinion.

**Comment by Roboe** [comment]
He has told me there shouldn't be any problem, but also advise us to contact support@carto.com for added certainty. I'll write tomorrow, I should sleep now, :sleeping:

**Comment by StefanBrand** [comment]
@Roboe Have you heard back from Carto support?

**Comment by Roboe** [comment]
Sorry for the delay.

I talked to Emilio from CARTO, and his response was affirmative.

Here is the legal part from CARTO's side Emilio kindly quoted to me:

> Thanks for reaching us out! Emilio here, from CARTO. Our [basemap service](https://carto.com/location-data-services/basemaps/) is delivered in two forms, as a free service and as a commercial service. The main difference between them are a number of restrictions on the free service [[Terms of Service](https://drive.google.com/file/d/0B3OBExqwT6KJaHdTcEVnYU8xYTg/view)] and the extended capabilities that the commercial service provides. You will require our commercial service if any of the following applies to you:
> 
> - The basemap is used inside an application or website that requires payment, is private or is used for asset-tracking. 
> - You require a Service Level Agreement on the basemap service. We do not provide any SLA’s on our free offering. 
> - You require more than 75,000 mapviews per month, which is the limit for our free service
> - You require a custom map design. On our free service we provide 2 map designs, Dark Matter and Positron.
> 
>When you get a commercial license you will get an api_key to attach to your tile requests. Our commercial basemap service starts at $600/year with 100,000 mapviews per month.
> 
> From the technical side, we offer the maps in raster format and in vector format in collaboration with Mapzen. To utilise the vector format you will need to use the Tangram library together with Leaflet.

Emilio said we fulfil all of the requisites if we don't expect to receive more than 75,000 mapviews each month. One mapview is defined as the loading of 15 tiles (256x256px). I feel like we won't exceed it for now. No problem embedding the map on Fairphone's website, either.

If at some point we exceed the mapviews/month limit, then we should talk to Fairphone for getting a commercial license.

**Comment by StefanBrand** [comment]
Sounds great! Maybe I'll have time to look into it next week, but you might as well do it, if you have the time. :)
