### ISSUE TITLE
Add page title and useful metadata

### ISSUE THREAD

**Issue by Roboe** [WeAreFairphone/fprsmap#21]
It just jumped right into my `<head>`; there's no `<title>` in the map! I didn't notice that until I readded it to my bookmarks due to the repo transfer.

We should probably enhance this addition at the same time with some rich metadata with [SiloBuster](https://autonome.github.io/silobuster/), as suggested in this recent [MozHacks post](https://hacks.mozilla.org/2016/09/vaulting-out-of-walled-gardens-with-fancy-links/)

Fields to discuss:
* Page Title
* Page Description
* Page URL
* Summary Image
* Publisher Twitter Handle
* Author Twitter Handle
* Content Type (Website/Article/Blog)
* Site Name

My quick shot:
* Page Title: The Fairphoner Map
* Page Description: A community map for the Fairphone community
* Page URL: https://wearefairphone.github.io/fprsmap/ (change it when we set up the Fairphone subdomain)
* Summary Image: https://avatars3.githubusercontent.com/u/22130441 (linked to the @WeAreFairphone's avatar)
* Publisher Twitter Handle: @WeAreFairphone (@Fairphone later?)
* Author Twitter Handle: @WeAreFairphone
* Content Type: Website
* Site Name: Fairphone Community

**Comment by StefanBrand** [comment]
Sounds good. As `Page Title` I'd use `Fairphoners Map` or `Fairphone Community Map`.

Can Github accounts be used in `* Twitter Handle`?

Am 16. September 2016 22:23:34 MESZ, schrieb "Roberto M.F." <notifications@github.com>:
>It just jumped right into my `<head>`; there's no `<title>` in the map!
>I didn't notice that until I readded it to my bookmarks due to the repo
>transfer.
>
>We should probably enhance this addition at the same time with some
>rich metadata with
>[SiloBuster](https://autonome.github.io/silobuster/), as suggested in
>this recent [MozHacks
>post](https://hacks.mozilla.org/2016/09/vaulting-out-of-walled-gardens-with-fancy-links/)
>
>Fields to discuss:
>* Page Title
>* Page Description
>* Page URL
>* Summary Image
>* Publisher Twitter Handle
>* Author Twitter Handle
>* Content Type (Website/Article/Blog)
>* Site Name
>
>My quick shot:
>* Page Title: The Fairphoner Map
>* Page Description: A community map for the Fairphone community
>* Page URL: https://wearefairphone.github.io/fprsmap/ (change it when
>we set up the Fairphone subdomain)
>* Summary Image: https://avatars3.githubusercontent.com/u/22130441
>(linked to the @WeAreFairphone's avatar)
>* Publisher Twitter Handle: @WeAreFairphone (@Fairphone later?)
>* Author Twitter Handle: @WeAreFairphone
>* Content Type: Website
>* Site Name: Fairphone Community

-- 
Diese Nachricht wurde von meinem Fairphone mit K-9 Mail gesendet.

**Comment by Roboe** [comment]
I don't think so, but I created yesterday the @WeAreFairphone Twitter [account](https://twitter.com/WeAreFairphone) for that matter, ;)

I'd go for Fairphone Community Map because of its clarity. What about the other fields? I'm specially interested in reviewing the Page Description

**Comment by StefanBrand** [comment]
I thought it was okay, but you challenged me to come up with something different:

"Need help with your Fairphone? Want to meet other Fairphoners? Or buy a Fairphone at a shop? This map shows you where!"

What do you think?

Am 17. September 2016 14:48:29 MESZ, schrieb "Roberto M.F." <notifications@github.com>:
>I don't think so, but I created yesterday the @WeAreFairphone Twitter
>[account](https://twitter.com/WeAreFairphone) for that matter, ;)
>
>I'd go for Fairphone Community Map because of its clarity. What about
>the other fields? I'm specially interested in reviewing the Page
>Description

-- 
Diese Nachricht wurde von meinem Fairphone mit K-9 Mail gesendet.

**Comment by Roboe** [comment]
That's a slogan, more than a description. Turning it the other way around, maybe?

> A community-made map for meeting other fairphoners, buying a Fairphone, or getting help with yours
[98](https://duckduckgo.com/?q=char+count+A+community-made+map+for+meeting+other+fairphoners%2C+buying+a+Fairphone%2C+or+getting+help+with+yours&ia=answer) chars (Twitter [recommends](https://dev.twitter.com/cards/markup) less than 200)

**Comment by StefanBrand** [comment]
What about: 
"A community-made map that shows where to meet other Fairphoners, get help with your Fairphone or buy a new one." [111](https://duckduckgo.com/?q=char+count+a+community-made+map+that+shows+where+to+meet+other+fairphoners%2C+get+help+with+your+fairphone+or+buy+a+new+one.&ia=answer)

PS: Personally I think "buying" should come last as it's not our focus. But that's only a detail.

Am 17. September 2016 16:57:34 MESZ, schrieb "Roberto M.F." <notifications@github.com>:
>That's a slogan, more than a description. Turning it the other way
>around, maybe?
>
>> A community-made map for meeting other fairphoners, buying a
>Fairphone, or getting help with yours
>[98](https://duckduckgo.com/?q=char+count+A+community-made+map+for+meeting+other+fairphoners%2C+buying+a+Fairphone%2C+or+getting+help+with+yours&ia=answer)
>chars (Twitter [recommends](https://dev.twitter.com/cards/markup) less
>than 200)

-- 
Diese Nachricht wurde von meinem Fairphone mit K-9 Mail gesendet.

**Comment by Roboe** [comment]
Yes, I agree with the "buying" position

I like that description! Gonna do a PR, then, :)
