### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by StefanBrand** [WeAreFairphone/fprsmap#23]
Apparently there is no standard on this, but I found this [w3c document](https://www.w3.org/2005/10/howto-favicon) from 2007.

**Comment by Roboe** [comment]
That's pretty standard, IMO:
```
<link rel="shortcut icon" href="https://developer.cdn.mozilla.net/static/img/favicon32.e02854fdcf73.png">
```
Source: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML#Adding_custom_icons_to_your_site

Ok, we have the code, we need the icon, :+1:

**Comment by StefanBrand** [comment]
I thought about simply using the blue marker. Or make a draw up using three or four (for the four Fairphone action areas) markers in different colours.

What do you think? 

Am 19. September 2016 14:24:46 MESZ, schrieb "Roberto M.F." <notifications@github.com>:
>That's pretty standard, IMO:
>```
><link rel="shortcut icon"
>href="https://developer.cdn.mozilla.net/static/img/favicon32.e02854fdcf73.png">
>```
>Source:
>https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML#Adding_custom_icons_to_your_site
>
>Ok, we have the code, we need the icon, :+1: 

-- 
Diese Nachricht wurde von meinem Fairphone mit K-9 Mail gesendet.

**Comment by Roboe** [comment]
![screenshot 2016-09-19 16-10-33](https://cloud.githubusercontent.com/assets/7013797/18635003/ac8768ec-7e83-11e6-814e-7500330f4941.png)

We need to cut it square, :/

I also think the markers composition would be too much information for such a tiny icon.

**Comment by StefanBrand** [comment]
I know. I would have added blank space on both sides.

**Comment by Roboe** [comment]
Great done!

I see now you are more skilled with git. Next time, can you make this kind of changes on the same commit?
Commit history is important for the long term, and there are some common practices too you can read about: https://github.com/erlang/otp/wiki/writing-good-commit-messages

(It's just some pickiness, don't take it personal!)

**Comment by StefanBrand** [comment]
I'm not taking it personal. Seeing the issue history it looks _really_ 
messy now! :blush:

Thank you for the link. I will read through it and improve my commit 
messages. :smile:

Is it possible to write an explanatory text directly in `git commit -m 
"[...]"`?


Am 19.09.2016 um 21:15 schrieb Roberto M.F.:

**Comment by Roboe** [comment]
No, the `-m` flag only allows you to write a commig short description. Without that (ie. `git commit` alone), a terminal text editor (`vim` by default, I recommend you to change to `nano`) opens, and then you can write the short message, double line break, long description, ;)

Or you could use a git GUI frontend like [gitg](https://wiki.gnome.org/Apps/Gitg#Download) (I like the command line, but use this from time to time) or [GitHub Desktop](https://desktop.github.com/)

**Comment by StefanBrand** [comment]
I configured git to default to Atom. Since Atom is built by Github it 
integrates nicely (you don't even have to give a path to the 
Atom-directory).

Am 19.09.2016 um 22:18 schrieb Roberto M.F.:
