### ISSUE TITLE
Have a proper README

### ISSUE THREAD

**Issue by StefanBrand** [WeAreFairphone/fprsmap#26]
In order to enable others to use the map, for example with the URI parameters, we should come up with an explanatory README.

**Comment by Roboe** [comment]
YES. I want to make it since just after you created the repo, 😂

**Comment by StefanBrand** [comment]
Since you have more experience in these things: What should a good README include? And what can't we miss, what has to be described in any case?

**Comment by Roboe** [comment]
I have some notes of a great talk @xuanxu gave us on h4ckademy:
> ## Care your README file
- Describe project
- Installation instructions
- Status of the project
- Basic use case/example
- Contact info

> README.md integrates with GitHub

Here are the complete notes: https://gitlab.com/snippets/26971

**Comment by xuanxu** [comment]
Happy to know you liked the talk, @Roboe!
Here are the slides in case you find them useful: https://speakerdeck.com/xuanxu/how-to-manage-an-open-source-project

**Comment by Roboe** [comment]
I really liked it! Thank you for the slides! :smiley:  :+1:

**Comment by StefanBrand** [comment]
Thank you for the notes and the slides! 😃 

I will look into them and write something up in the following days.

**Comment by StefanBrand** [comment]
Thank you! Would have been an awful work for me to rebase my fork and create a PR.
-- 
This message was sent from my Fairphone 1 with K-9 Mail.

Am 14. Dezember 2016 00:51:34 MEZ schrieb "Roberto M.F." <notifications@github.com>:
>Since you already did the work of writing it in your fork, I've
>cherrypicked the commit and pushed it to the main repo, ;)
