### ISSUE TITLE
Add link to this repo in lower right corner of the map

### ISSUE THREAD

**Issue by StefanBrand** [WeAreFairphone/fprsmap#30]
Next to the "OSM contributors" link there should be an *About* link directing to this repo's main page (README).

**Comment by Roboe** [comment]
I agree. We can do this once we change basemap tiles (#20), because we'll need to credit CARTO too.

**Comment by Roboe** [comment]
What about this?

> Leaflet | &copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, &copy; <a href="https://carto.com/attributions">CARTO</a> | &copy; <a href="https://github.com/WeAreFairphone/fprsmap">WeAreFairphone</a> (<a href="https://www.gnu.org/licenses/gpl-3.0.en.html">GPLv3</a>)

```
&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, &copy; <a href="https://carto.com/attributions">CARTO</a> | &copy; <a href="https://github.com/WeAreFairphone/fprsmap">WeAreFairphone</a> (<a href="https://www.gnu.org/licenses/gpl-3.0.en.html">GPLv3</a>)
```

**Comment by StefanBrand** [comment]
It's not really copy*right*, is it? ;) 

I was wondering if we need something more inviting, such as "Help us improve this map!", linking to Github. What do you think?
-- 
This message was sent from my Fairphone 1 with K-9 Mail.

Am 15. Dezember 2016 02:40:25 MEZ schrieb "Roberto M.F." <notifications@github.com>:
>What about this?
>
>> Leaflet | &copy; <a
>href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>
>contributors, &copy; <a href="https://carto.com/attributions">CARTO</a>
>| &copy; <a
>href="https://github.com/WeAreFairphone/fprsmap">WeAreFairphone</a> (<a
>href="https://www.gnu.org/licenses/gpl-3.0.en.html">GPLv3</a>)
>
>```
>&copy; <a
>href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>
>contributors, &copy; <a href="https://carto.com/attributions">CARTO</a>
>| &copy; <a
>href="https://github.com/WeAreFairphone/fprsmap">WeAreFairphone</a> (<a
>href="https://www.gnu.org/licenses/gpl-3.0.en.html">GPLv3</a>)
>```

**Comment by Roboe** [comment]
I opened the pull request, let's discuss the text there, ;)

**Comment by StefanBrand** [comment]
Let's stick with "WeAreFairphone". It's just the cleanest way, even if some people might click the other links first, when they want to contact us.

**Comment by Roboe** [comment]
Ok, great! :)
