### ISSUE TITLE
Upgrade to Leaflet 1.x

### ISSUE THREAD

**Issue by StefanBrand** [WeAreFairphone/fprsmap#34]
We should upgrade to the latest Leaflet release because I think it makes #27 easier to implement.

PS.: [Here ](http://leafletjs.com/2016/09/27/leaflet-1.0-final.html)is the blog entry for the 1.0.0 release.

**Comment by Roboe** [comment]
This is the next thing I was planning to do, in fact. Thanks for the issue, :+1:

We need to check the Leaflet.FeatureGroup.SubGroup plugin compatiblity or check if Leaflet 1.x now includes some kind of marker grouping
