### ISSUE TITLE
Improve UX on touch screen devices

### ISSUE THREAD

**Issue by StefanBrand** [WeAreFairphone/fprsmap#35]
Today I had a cousin test the map on my Fairphone 1 and he told me several difficulties he discovered:

- Layer control check boxes are too small
- the content of the marker popups is too small
- often when you click on a marker, the map moves instead of that the popup opens

**Comment by StefanBrand** [comment]
Connected in a way to #31.

**Comment by StefanBrand** [comment]
> often when you click on a marker, the map moves instead of that the popup opens

Can't reproduce this on my Fairphone 1. Must be his Nexus... ;)

**Comment by Roboe** [comment]
...or his fingers

**Comment by StefanBrand** [comment]
There is the [`L.Browser` object](http://leafletjs.com/reference.html#browser). Do we want to have special code for mobile devices, or apply bigger design elements for all environments (desktop too)?

**Comment by StefanBrand** [comment]
I guess, this is the way to go: [Introduction to CSS Media Queries](http://www.htmlgoodies.com/beyond/css/introduction-to-css-media-queries.html)

**Comment by Roboe** [comment]
I prefer bigger design for `media="all"`. Less complexity for us, and desktop users are getting used to bigger elements anyway (Material Design is everywhere)

**Comment by StefanBrand** [comment]
Ok, my first attempt is to make the check boxes bigger. I'll have to read myself into CSS a bit.

**Comment by StefanBrand** [comment]
> often when you click on a marker, the map moves instead of that the popup opens

If this pops up, there is a way to fix it: http://leafletjs.com/reference-1.0.2.html#map-taptolerance
