### ISSUE TITLE
Implement reverse geocoding

### ISSUE THREAD

**Issue by StefanBrand** [WeAreFairphone/fprsmap#4]
It would be great, if people could just type in their location and the map would find out longitude and latitude on its own.

**Comment by Roboe** [comment]
What would be the purpose for this kind of interaction? Only introduce new points or move the map view to your location?

**Comment by newluck77** [comment]
The former. At the moment I go to http://nominatim.openstreetmap.org/ to find out the coordinates of a city/location. It would be great to automate this. A user would then only have to give `loc` and the address lookup feature would output the coordinates automatically.

**Comment by newluck77** [comment]
Maybe Fairphone will provide workforce to implement this.

**Comment by newluck77** [comment]
The more I think about this, the more I think this should be done on the FP server side. Together with the GUI for entering data, they could provide a field with a drop down that automatically lets you choose a city/address as you type. Thus only coordinates would get passed to the map.
