### ISSUE TITLE
Fullscreen button does nothing if fullscreen is not allowed

### ISSUE THREAD

**Issue by StefanBrand** [WeAreFairphone/fprsmap#48]
https://developer.mozilla.org/en-US/docs/Web/API/Document/fullscreenEnabled
https://github.com/Leaflet/Leaflet.fullscreen

**Comment by Roboe** [comment]
We can check if the map is inside an `iframe` with `window.self===window.top`. This, however, doesn't mean the iframe can't use the Fullscreen API. If false, we can not enable the fullscreen plugin as a workaround.

**Comment by StefanBrand** [comment]
The issue is that Discourse strips out the `allowfullscreen="true"` part 
from the iframe. Check it out in the Firefox Inspector.

Am 11.01.2017 um 16:40 schrieb Roberto M.F.:

**Comment by Roboe** [comment]
Yes, I know. We can't do anything about that, it's not our content.

**Comment by StefanBrand** [comment]
I wonder if the fullscreen feature is very useful anyway. It's not 
widely used  (Gxxgle maps doesn't use it, for example).


Am 11.01.2017 um 16:53 schrieb Roberto M.F.:

**Comment by Roboe** [comment]
Sure, I only see the usefulness of a fullscreen button when the map is embeded, but anything significant, though.
Should we remove the fullscreen feature once and for all then?

**Comment by StefanBrand** [comment]
Can we display a link to the full map on all pages that are not the full 
map itself?

Am 11.01.2017 um 17:02 schrieb Roberto M.F.:

**Comment by Roboe** [comment]
Yes, with the `window.self !== window.top` I wrote above. If `true`, show a label with a link to the full map.

**Comment by StefanBrand** [comment]
Ah Ok, that's that.

Am 11.01.2017 um 17:17 schrieb Roberto M.F.:

**Comment by StefanBrand** [comment]
I need help with this. Using [easyButton](https://github.com/CliffCloud/Leaflet.EasyButton) I tried to make a button with a link. Unfortunately the icon is not centred...


Demo is at https://stefanbrand.github.io/fprsmap/, to test this, copy the following code into an empty .html-file:

```html
<head>
</head>
<body>
<iframe src="https://stefanbrand.github.io/fprsmap/" width="100%" height="400" allowfullscreen="true" frameborder="0">
 	 <p><a href="https://wearefairphone.github.io/fprsmap/" target="_blank">See the Fairphone Community Map!</a></p>
</iframe>
</body>
```

**Comment by Roboe** [comment]
Open a PR so I'd be able to push some code

**Comment by StefanBrand** [comment]
I opened the PR. At the moment I can't do any coding...

**Comment by StefanBrand** [comment]
I have an alternative solution: We could simply add a text link to the attribution control:

http://leafletjs.com/reference-1.0.3.html#control-attribution

It might be more intuitive than a fullscreen button that doesn't do fullscreen, but leads to an external page.
