### ISSUE TITLE
Panning left or right leads to parallel worlds

### ISSUE THREAD

**Issue by StefanBrand** [WeAreFairphone/fprsmap#49]
Implement `maxBounds`: http://leafletjs.com/reference.html#map-maxbounds

**Comment by Roboe** [comment]
What about [`worldCopyJump`](http://leafletjs.com/reference.html#map-worldcopyjump) instead of bounds?

**Comment by StefanBrand** [comment]
Yeah, that widens our horizon! B-)

That's a better solution!

Am 11.01.2017 um 15:27 schrieb Roberto M.F.:

**Comment by Roboe** [comment]
For some reason, GitHub couldn't build my `gh-pages` branch. It builds fine on local, though.

```
The page build failed with the following error:

unable to build page. Please try again later.

For information on troubleshooting Jekyll see:

  https://help.github.com/articles/troubleshooting-jekyll-builds

If you have any questions you can contact us by replying to this email.
```

**Comment by StefanBrand** [comment]
Works fine here:
![grafik](https://cloud.githubusercontent.com/assets/8948865/21852868/17067c4a-d815-11e6-9f65-ed8e7bf1330b.png)

**Comment by Roboe** [comment]
That's the penultimate commit. Span to another world (left or right), you will see it doesn't work

**Comment by StefanBrand** [comment]
Ok. Well, then "Please try again later." ;)

**Comment by Roboe** [comment]
I'll open a PR and let them build it on the upstream repo, better
