### ISSUE TITLE
Show physical touch points / shops on the map

### ISSUE THREAD

**Issue by StefanBrand** [WeAreFairphone/fprsmap#56]
The csv files for the physical touch points are up! :D -> 3b25cfe874cebc16cadf7fe1d69fe785f58b5ae1

I wonder though, how we will make use of them. Maybe using something like https://github.com/lastlegion/anyToJSON ?

**Comment by StefanBrand** [comment]
I'm having an issue here: The csv files don't have coordinates, so I implemented ESRI's Geocoding service. Problem is that the process is awfully slow!

Demo: https://stefanbrand.github.io/fprsmap/

**Comment by StefanBrand** [comment]
I have written a script for node.js that reads in the csv, geocodes them and puts out a json file for us to process. Unfortunately not all addresses are recognized as yet, so some markers aren't on the correct locations...

**Comment by Roboe** [comment]
Awesome! I'll review it soon. DId you update the node.js script? It would be great to have a look at it, too

**Comment by StefanBrand** [comment]
Haha, I did it already 3 months ago, but never uploaded it. A demo of the result (the geocoded shops) can be found here: 

https://stefanbrand.github.io/fprsmap/

Two of them, in the middle of Germany, have nothing or undefined as popup content...
-- 
This message was sent from my Fairphone 1 with K-9 Mail.

Am 16. Mai 2017 22:47:08 MESZ schrieb "Roberto M.F." <notifications@github.com>:
>Awesome! I'll review it soon. DId you update the node.js script? It
>would be great to have a look at it, too

**Comment by StefanBrand** [comment]
Opening hours are added too: https://github.com/StefanBrand/fprsmap/commit/fb2cc088e8b0b021b9f6d8b1dfc932dd8d0b626d :)
