### ISSUE TITLE
GUI for entering local Fairphoners communities

### ISSUE THREAD

**Issue by StefanBrand** [WeAreFairphone/fprsmap#7]
Have a :heavy_plus_sign:  button and a popup where people can add new Fairphone communities to the map. (Would be best in conjunction with #4 reverse geocoding.)

**Comment by Roboe** [comment]
I've been thinking about proper and easy solutions to this. There's a solution involving an `<iframe>`, but I don't know what kind of control we would have over the interaction flow ocurring inside the said `<iframe>`. Also, it should be as easy as possible for non-developers, and we have technical limitations (i.e. all our code is frontend).

Anyway, we should implement #8 before that. Let me chew it a bit more meanwhile.

**Comment by newluck77** [comment]
This will be obsolete as very probably Fairphone will provide a database on their website, where people can add data. We will be able to fetch that data and it will go online immediately.

**Comment by Roboe** [comment]
Woa! That' be awesome and solve the collaboration issue! :D

**Comment by newluck77** [comment]
Exactly! Maybe you have some comments on how to implement this in the best way? Using some kind of SQL?

**Comment by Roboe** [comment]
No suggestion at all on the backend implementation (the map is implementation-agnostic). We just need them to expose a public endpoint (i.e. no auth required) for each layer markers with JSON data and CORS enabled, :dancer:
