### ISSUE TITLE
Embed code does not reflect initial map layers

### ISSUE THREAD

**Issue by StefanBrand** [WeAreFairphone/fprsmap#71]
Example: Load `https://wearefairphone.github.io/fprsmap/?show=angels,events,shops` in your browser.

The embed popup will only insert the default map layers in the code, which are at the moment `angels,events`.

**Comment by Ingo-FP-Angel** [comment]
Is this bug still relevant? As far as I can see, only angels and events are supported anyway now.

**Comment by StefanBrand** [comment]
The embed case says 

```<iframe src="https://map.fairphone.community/?show=angels,events" width="100%" height="400" allowfullscreen="true" frameborder="0">
<p><a href="https://map.fairphone.community/?show=angels,events" target="_blank">See the Fairphone Community Map!</a></p>
</iframe>
```
in any case, even though you enter `https://map.fairphone.community/?show=angels` in the address bar. So yes, this is still relevant, but very minor.

**Comment by Ingo-FP-Angel** [comment]
Ok, got it, the bug happens when using the query params to show a non-default list of layers and _before_ changing the layers manually.
