### ISSUE TITLE
Add future Munich meetups

### ISSUE THREAD

**Issue by StefanBrand** [WeAreFairphone/fprsmap#74]
Our current data only covers the February meetup in Munich. We need to add the dates after February.

@Ingo-FP-Angel Maybe you want to tackle this one? 🙂

**Comment by Ingo-FP-Angel** [comment]
Ah, dammit, did the commit but forgot to associate this issue :(

**Comment by StefanBrand** [comment]
No problem, I can reference it in the merge commit. 🙂  Thanks a lot!!! 

PS.: This should have arrived hours ago, but it was never posted by Github. No idea why this was the case... 🤔
