### ISSUE TITLE
Pull events from the forum

### ISSUE THREAD

**Issue by StefanBrand** [WeAreFairphone/fprsmap#82]
The agenda view of the Fairphone forum has a simple `.json` file available:

https://forum.fairphone.com/c/community/l/agenda.json

It _should_ be relatively easy to dynamically pull this `.json` <s>and display it on the map.</s> @Roboe Could you give an opinion on this? Do you see any challenges? 

Edit: 🙄 Ok, those topics don't have geographical information as yet, unless we enable the [location plugin ](https://meta.discourse.org/t/locations-plugin/69742?u=stefan_fairphone) for Discourse... 😛

**Comment by Roboe** [comment]
Oh! That's a clever idea.

We should however only rely on the stable API that the agenda plugin gives us, though, which seems to be `<root>.topic_list.topics[index].event`.

According to a test server posted in [this Discourse Meta topic](https://meta.discourse.org/t/events-plugin-calendar/69776), with the location plugin you mention we would have a `<root>.topic_list.topics[index].location` object handy, with name, coordinates and address:

![captura de pantalla de 2018-06-24 16-19-12](https://user-images.githubusercontent.com/7013797/41819982-6ddedde0-77ca-11e8-9d99-9bb4f6f60c53.png)

**Comment by Roboe** [comment]
No, we'd loop through the topics in the `agenda.json` link you provided, which already lists only topics with events. At the time, this counts 4 topics, :)

**Comment by StefanBrand** [comment]
Ah, ok I get what you mean. I thought you were talking about the _whole_ topic list. I saw that the topics have their own `event` object. The additional `location` object would be ideal for our purposes.

**Comment by StefanBrand** [comment]
The agenda is at https://forum.fairphone.com/agenda.json now :)
