### ISSUE TITLE
topic.location is undefined

### ISSUE THREAD

**Issue by StefanBrand** [WeAreFairphone/fprsmap#91]
Console output: TypeError: topic.location is undefined ... [main.js:232:14](https://github.com/WeAreFairphone/fprsmap/blob/b09a1738d70bb93706576ad40c8ee82f05596d8e/js/main.js#L232)

[EFCT19](https://forum.fairphone.com/t/efct19-european-fairphoners-community-trip-to-amsterdam-2019-25-8-31-8/48657) (Amsterdam) is missing from map.

**Comment by Ingo-FP-Angel** [comment]
I think an event without location cannot be shown anyway, so I'd skip those.

But today I also noticed that once there is an event without location, other events in the JSON that follow the one without location aren't rendered either.

So I would just fix the second part of the issue (and not find ways to show events without a location).
