### ISSUE TITLE
Deployment fails

### ISSUE THREAD

**Issue by Ingo-FP-Angel** [WeAreFairphone/fprsmap#93]
The last CI builds at https://travis-ci.org/WeAreFairphone/fprsmap/builds all failed.

From the latest log https://travis-ci.org/WeAreFairphone/fprsmap/builds/625441044 in the "Deploying application" step:

``` 
Couldn't push the build to github.com/WeAreFairphone/fprsmap.git:gh-pages
```

**Comment by StefanBrand** [comment]
See https://github.com/WeAreFairphone/fpangels-hp/issues/10#issuecomment-566166026

**Comment by Ingo-FP-Angel** [comment]
Fixed, see https://github.com/WeAreFairphone/fpangels-hp/issues/10#issuecomment-568327365
